# 由于未创建CRD的api对象及控制器等，需手动添加该配置
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-v1-deployment
    failurePolicy: Fail
    name: mdeployment.kb.io
    rules:
    - apiGroups:
      - apps
      apiVersions:
      - v1
      operations:
      - CREATE
      - UPDATE
      resources:
      - deployments
    sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
  - admissionReviewVersions:
    - v1
    - v1beta1
    clientConfig:
      service:
        name: webhook-service
        namespace: system
        path: /validate-v1-deployment
      failurePolicy: Ignore
      name: vdeployment.kb.io
      rules:
      - apiGroups:
        - apps
        apiVersions:
        - v1
        operations:
        - CREATE
        - UPDATE
        resources:
        - deployments
      sideEffects: None
